#!/bin/sh
. ./Common

###############################################################################

try "fan: 0:100" <<EOF
/fan/profile:0:100
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:100
EOF

# -----------------------------------------------------------------------------

try "fan: 20:50 70:100" <<EOF
/fan/profile:20:50 70:100
/temp/0/current:0
/temp/0/current:30
/temp/0/current:60
/temp/0/current:90
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:100
/fan/all/pwm-set:50
/fan/all/pwm-set:60
/fan/all/pwm-set:90
/fan/all/pwm-set:100
EOF

# -----------------------------------------------------------------------------

try "fan: 49:0 50:20 80:100" <<EOF
/fan/profile:49:0 50:20 80:100
/temp/0/current:40
/temp/0/current:50
/temp/0/current:65
/temp/0/current:90
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:100
/fan/all/pwm-set:0
/fan/all/pwm-set:20
/fan/all/pwm-set:60
/fan/all/pwm-set:100
EOF

# -----------------------------------------------------------------------------

try "fan: 20:20 80:100, temperature set to 35 C" <<EOF
/temp/0/current:35
/fan/profile:20:20 80:100
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:40
EOF

# -----------------------------------------------------------------------------

try "fan: 49:0 50:30 90:100, temperature set to 70.5 C" <<EOF
/temp/0/current:70.5
/fan/profile:49:0 50:30 90:100
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:65
EOF

# -----------------------------------------------------------------------------

try "fan: 50:0 50:30 90:100, temperature set to 70.5 C (entry ignored)" <<EOF
/temp/0/current:70.5
/fan/profile:50:0 50:30 90:100
EOF

expect <<EOF
bad temp:duty entry at "50:30 90:100"
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:50
EOF

###############################################################################
