#!/bin/sh
. ./Common

###############################################################################

CFG_SWITCH_LAST=off CFG_SLOT0_SWITCH_LAST=off \
    try "offon: master+slot0 off-on for running single mined" <<EOF
/power/on/master:0
/power/on/slot0:0
/power/on/master:1
/power/on/slot0:1
/daemon/mined/time:123
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_LAST/set:
/config/user0/SWITCH_LAST/set:
/daemon/mined/start:x
UP
EOF

# -----------------------------------------------------------------------------

CFG_SWITCH_LAST=off \
    try "offon: master off-on for running single mined" <<EOF
/power/on/master:0
/power/on/slot0:1
/power/on/master:1
/daemon/mined/time:123
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_LAST/set:
/daemon/mined/start:x
UP
EOF

###############################################################################
