#!/bin/sh
. ./Common

###############################################################################
 
CFG_SEPARATE_MINED=y CFG_SLOT0_SERIAL=xyz \
    CFG_SWITCH_LAST=off CFG_SWITCH_0_LAST=off \
    try "offon: master+slot0 off-on for running single mined" <<EOF
/power/on/master:0
/power/on/slot0:0
/power/on/master:1
/power/on/slot0:1
/daemon/mined0/time:123
EOF
 
expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_LAST/set:
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined0/start:x
READY 0
EOF
 
# -----------------------------------------------------------------------------
 
CFG_SEPARATE_MINED=y CFG_SLOT0_SERIAL=xyz \
    CFG_SWITCH_LAST=off \
    try "offon: master off-on for running single mined" <<EOF
/power/on/master:0
/power/on/slot0:1
/power/on/master:1
/daemon/mined0/time:123
EOF
 
expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_LAST/set:
LHADM 0 up
/daemon/mined0/start:x
READY 0
EOF

###############################################################################
