#!/bin/sh
. ./Common

###############################################################################

try "onoff: master+slot0 on for running single mined" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined/time:123
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/daemon/mined/start:x
UP
EOF

# -----------------------------------------------------------------------------

try "onoff: master+slot0 on then master off (no overlap) for single mined" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined/time:123
/power/on/master:0
/daemon/mined/time:0
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/daemon/mined/start:x
UP
/config/user/SWITCH_LAST/set:off
/daemon/mined/stop:x
LHADM  down
EOF

# -----------------------------------------------------------------------------

try "onoff: master on then off (with overlap) for single mined" <<EOF
/power/on/master:1
/power/on/slot0:1
/power/on/master:0
/daemon/mined/time:123
/daemon/mined/time:0
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/daemon/mined/start:x
/config/user/SWITCH_LAST/set:off
/daemon/mined/stop:x
LHADM  down
EOF

# -----------------------------------------------------------------------------

try "onoff: master on-off-on (overlap on off-on) for single mined" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined/time:123
/power/on/master:0
/power/on/master:1
/daemon/mined/time:0
/daemon/mined/time:123
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/daemon/mined/start:x
UP
/config/user/SWITCH_LAST/set:off
/daemon/mined/stop:x
/config/user/SWITCH_LAST/set:
/daemon/mined/start:x
UP
EOF

# -----------------------------------------------------------------------------

try "onoff: master on with manual stop for single mined" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined/time:123
/daemon/mined/time:0
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/daemon/mined/start:x
UP
MANUAL STOP ?
EOF

# -----------------------------------------------------------------------------

try "onoff: slot 0 on-off for running single mined" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined/time:123
/power/on/slot0:0
/daemon/mined/time:0
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/daemon/mined/start:x
UP
/config/user0/SWITCH_LAST/set:off
/daemon/mined/stop:x
LHADM  down
EOF

# -----------------------------------------------------------------------------

try "onoff: slot 1 on-off for running single mined (does nothing)" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined/time:123
/power/on/slot1:0
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/daemon/mined/start:x
UP
/config/user1/SWITCH_LAST/set:off
EOF

###############################################################################
