#!/bin/sh
. ./Common

###############################################################################

CFG_SLOT0_SERIAL=xyz CFG_SLOT1_SERIAL=xyz \
    try "onoffsngtwo: master+slot0 on" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined/time:123
EOF

expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined/start:x
READY
EOF

# -----------------------------------------------------------------------------

CFG_SLOT0_SERIAL=xyz CFG_SLOT1_SERIAL=xyz \
    try "onoffsngtwo: master+slots on then master off (no overlap)" <<EOF
/power/on/master:1
/power/on/slot0:1
/power/on/slot1:1
/daemon/mined/time:123
/daemon/mined/time:0
/daemon/mined/time:123
/power/on/master:0
/daemon/mined/time:0
EOF

expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined/start:x
/config/user/SWITCH_1_LAST/set:
/daemon/mined/stop:x
LHADM 1 up
/daemon/mined/start:x
READY
/config/user/SWITCH_LAST/set:off
/daemon/mined/stop:x
LHADM 0 down
LHADM 1 down
EOF

# -----------------------------------------------------------------------------

CFG_SLOT0_SERIAL=xyz CFG_SLOT1_SERIAL=xyz \
    try "onoffsngtwo: master+slots on then slot0 off (no overlap)" <<EOF
/power/on/master:1
/power/on/slot0:1
/power/on/slot1:1
/daemon/mined/time:123
/daemon/mined/time:0
/daemon/mined/time:123
/power/on/slot0:0
/daemon/mined/time:0
/daemon/mined/time:123
EOF

expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined/start:x
/config/user/SWITCH_1_LAST/set:
/daemon/mined/stop:x
LHADM 1 up
/daemon/mined/start:x
READY
/config/user/SWITCH_0_LAST/set:off
/daemon/mined/stop:x
LHADM 0 down
/daemon/mined/start:x
READY
EOF

# -----------------------------------------------------------------------------

CFG_SLOT0_SERIAL=xyz CFG_SLOT1_SERIAL=xyz \
    try "onoffsngtwo: master+slots on then slot1 off (no overlap)" <<EOF
/power/on/master:1
/power/on/slot0:1
/power/on/slot1:1
/daemon/mined/time:123
/daemon/mined/time:0
/daemon/mined/time:123
/power/on/slot1:0
/daemon/mined/time:0
/daemon/mined/time:123
EOF

expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined/start:x
/config/user/SWITCH_1_LAST/set:
/daemon/mined/stop:x
LHADM 1 up
/daemon/mined/start:x
READY
/config/user/SWITCH_1_LAST/set:off
/daemon/mined/stop:x
LHADM 1 down
/daemon/mined/start:x
READY
EOF

# -----------------------------------------------------------------------------

CFG_SLOT0_SERIAL=xyz CFG_SLOT1_SERIAL=xyz \
    try "onoffsngtwo: master+slots on then slot1 off-on (no overlap)" <<EOF
/power/on/master:1
/power/on/slot0:1
/power/on/slot1:1
/daemon/mined/time:123
/daemon/mined/time:0
/daemon/mined/time:123
/power/on/slot1:0
/daemon/mined/time:0
/daemon/mined/time:123
/power/on/slot1:1
/daemon/mined/time:0
/daemon/mined/time:123
EOF

expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined/start:x
/config/user/SWITCH_1_LAST/set:
/daemon/mined/stop:x
LHADM 1 up
/daemon/mined/start:x
READY
/config/user/SWITCH_1_LAST/set:off
/daemon/mined/stop:x
LHADM 1 down
/daemon/mined/start:x
READY
/config/user/SWITCH_1_LAST/set:
/daemon/mined/stop:x
LHADM 1 up
/daemon/mined/start:x
READY
EOF

###############################################################################
