#!/bin/sh
. ./Common

###############################################################################
 
CFG_SEPARATE_MINED=y \
    CFG_SLOT0_SERIAL=xyz \
    try "ooshut: temperature shutdown cuts power" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined0/time:123
/temp/shutdown:1 3
/daemon/mined0/time:0
EOF
 
expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined0/start:x
READY 0
/sys/led/rgb:R 500 500
/daemon/mined0/stop:x
LHADM 0 down
EOF
 
# -----------------------------------------------------------------------------

CFG_SEPARATE_MINED=y \
    CFG_SLOT0_SERIAL=xyz \
    try "ooshut: temperature shutdown cuts master switch (TRIP_MASTER)" <<EOF
/config/user/TRIP_MASTER:y
/power/on/master:1
/power/on/slot0:1
/daemon/mined0/time:123
/temp/shutdown:1 3
/daemon/mined0/time:0
/power/on/master:0
EOF
 
expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined0/start:x
READY 0
/sys/led/rgb:R 500 500
/power/on/master:0
/daemon/mined0/stop:x
LHADM 0 down
/config/user/SWITCH_LAST/set:off
EOF
 
# -----------------------------------------------------------------------------

CFG_SEPARATE_MINED=y \
    CFG_SLOT0_SERIAL=xyz \
    try "ooshut: clearing shutdown does restore power" <<EOF
/power/on/master:1
/power/on/slot0:1
/daemon/mined0/time:123
/power/shutdown:1 1
/daemon/mined0/time:0
/sys/clear-shutdown:x
/power/shutdown:0 0
/daemon/mined0/time:123
EOF
 
expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined0/start:x
READY 0
/sys/led/rgb:R 500 500
/daemon/mined0/stop:x
LHADM 0 down
RUN pshut clear
/sys/led/rgb:RG 0 0
LHADM 0 up
/daemon/mined0/start:x
READY 0
EOF
 
# -----------------------------------------------------------------------------
 
CFG_SEPARATE_MINED=y \
    CFG_SLOT0_SERIAL=xyz \
    try "ooshut: clearing shutdown does not restore power (TRIP_MASTER)" <<EOF
/config/user/TRIP_MASTER:y
/power/on/master:1
/power/on/slot0:1
/daemon/mined0/time:123
/power/shutdown:1 1
/daemon/mined0/time:0
/power/on/master:0
/sys/clear-shutdown:x
/power/shutdown:0 0
EOF
 
expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined0/start:x
READY 0
/sys/led/rgb:R 500 500
/power/on/master:0
/daemon/mined0/stop:x
LHADM 0 down
/config/user/SWITCH_LAST/set:off
RUN pshut clear
/sys/led/rgb:RG 0 0
EOF
 
# -----------------------------------------------------------------------------

CFG_SEPARATE_MINED=y \
    CFG_SLOT0_SERIAL=xyz \
    try "ooshut: clear shutdown, then power up (TRIP_MASTER)" <<EOF
/config/user/TRIP_MASTER:y
/power/on/master:1
/power/on/slot0:1
/daemon/mined0/time:123
/power/shutdown:1 1
/daemon/mined0/time:0
/power/on/master:0
/sys/clear-shutdown:x
/power/shutdown:0 0
/power/on/master:1
/daemon/mined0/time:123
EOF
 
expect <<EOF
/power/on/ops:0x0 0x0 1
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/config/user/SWITCH_0_LAST/set:
LHADM 0 up
/daemon/mined0/start:x
READY 0
/sys/led/rgb:R 500 500
/power/on/master:0
/daemon/mined0/stop:x
LHADM 0 down
/config/user/SWITCH_LAST/set:off
RUN pshut clear
/sys/led/rgb:RG 0 0
/config/user/SWITCH_LAST/set:
LHADM 0 up
/daemon/mined0/start:x
READY 0
EOF
 
###############################################################################
