#!/bin/sh
. ./Common

###############################################################################

CFG_SLOT0_SERIAL=x try "fault: total tsense fault causes max fan speed" <<EOF
/fan/profile:20:20 90:90
@60
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:100
/sys/led/rgb:RG 100 100
/temp/0/overdue:60 0,3,60 2,1,60 4,7,60 6,5,60 8,11,60 10,9,60 12,15,60 14,13,60 16,19,60 18,17,60 20,23,60 22,21,60 24,27,60 26,25,60 28,31,60 30,29,60 32,35,60 34,33,60 36,39,60 38,37,60 40,43,60 42,41,60 44,47,60 46,45,60 48,51,60 50,49,60 52,55,60 54,53,60 56,59,60 58,57,60 60,63,60 62,61,60
EOF

# -----------------------------------------------------------------------------

CFG_SLOT0_SERIAL=x try "fault: tsense stopping causes max fan speed" <<EOF
/temp/0/current:`temp 10 0:-`
/fan/profile:20:20 100:90
@20
>20
/temp/0/current:`temp 10 0:- 38:-`
>40
@40
/temp/0/current:`temp 10 0:- 38:-`
>60
@60
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:20
20
/fan/all/pwm-set:20
40
/sys/led/rgb:RG 100 100
/temp/0/overdue:40 62,61,40
/fan/all/pwm-set:100
60
EOF

# -----------------------------------------------------------------------------

CFG_SLOT0_SERIAL=x try "fault: tsense recovery resumes old fan speed" <<EOF
/temp/0/current:`temp 30 0:-`
/fan/profile:20:20 100:100
@20
>20
/temp/0/current:`temp 30 0:- 38:-`
>40
@40
>50
/temp/0/current:`temp 30`
@50
EOF

expect <<EOF
/sys/led/rgb:RG 0 0
/sys/led/ether:1
/fan/all/pwm-set:30
20
/fan/all/pwm-set:30
40
/sys/led/rgb:RG 100 100
/temp/0/overdue:40 62,61,40
50
/sys/led/rgb:RG 0 0
/temp/0/overdue:
/fan/all/pwm-set:30
EOF

###############################################################################
